configs/offline.toml, configs/online.toml, core/src/config.rs, filtergen/src/lib.rs
Adds a configuration option to suppress DPDK runtime log and telemetry outputs.
Removes predicate trie display during compilation to avoid clutter.
=> Reduce output

configs/online-vdev.toml, core/src/config.rs, core/src/lcore/monitor.rs, core/src/port/mod.rs
Add the dpdk_supl_args argument to pass arguments such as ["--no-huge","--no-pci"] allowing to try Retina in restricted environment, i.e. with Docker using PCAP virtual device (https://doc.dpdk.org/guides/nics/pcap_ring.html).
Also, if RSS is not supported do not fail but warn the user.
Similarly, if some statistics are not available, do not fail but warn
the user.
Verify that the MTU is in the device constraint. If setting it is not
supported, do not fail but warn user.
Verify the VLAN_STRIP offload is possible. If not, just don't activate
it.
=> Allow to pass supplementary arguments and relax device constraints

Cargo.toml, core/src/dpdk/mod.rs, core/src/lib.rs, core/src/runtime/mod.rs, examples/spin/Cargo.toml, examples/spin/README.md, examples/spin/src/main.rs
Reduces visibility of the DPDK module to crate-private.
Adds an example to approximate callback complexity by busy looping for a given number of cycles.
=> Spin example

configs/online-vdev.toml
In general VDEVs are not able to change the MTU, and do not support scattering. So if GRO is enabled packets will be truncated and malformed.
@thegwan is there a way to support truncated packets? It would be interesting as traces are often truncated too.
=> VDEV: Set default MTU to 65535

core/src/protocols/packet/ipv4.rs, core/src/protocols/packet/tcp.rs
- For convenience, adds some more accessor methods for IPv4 and TCP header fields.
- Adds some missing documentation.
=> More accessor methods for IPv4 and TCP modules

core/src/dpdk/mod.rs, core/src/lib.rs
Makes the `rte_lcore_id()` function public
=> Expose rte_lcore_id

INSTALL.md
Added notes to INSTALL.md: 
- Can run Retina offline out of the box on a VM
- Link to bug for meson build failure with DPDK 21.08 
- Basic changes needed for ARM-based VMs
=> Install instr

.github/workflows/ci.yml, .github/workflows/rustdoc.yml, Cargo.toml, core/Cargo.toml, core/build.rs, core/src/filter/hardware/flow_action.rs, core/src/filter/hardware/mod.rs, core/src/memory/mbuf.rs, core/src/runtime/online.rs, core/src/subscription/frame.rs, core/src/subscription/zc_frame.rs
Updates CI toolchain to Rust 1.75.0 and fixes a couple of build and clippy style warnings. 
The workspace resolver is updated to explicitly specify `resolver = "2"` to remove the build warning, see: https://doc.rust-lang.org/cargo/reference/resolver.html#resolver-versions
=> Update rustdoc CI rustc version to 1.75.0

.github/workflows/rustdoc.yml
The default LLVM and Clang versions that come with the latest Ubuntu (22.04) in the Rustdoc workflow seems to have compatibility issues with bindgen. Removing v14.0.0 and v13.0.0 fixes the issue.
=> Fix bindgen and clang compatibility in Rustdoc workflow

INSTALL.md, core/build.rs, core/src/port/mod.rs
- Troubleshooting bindgen + clang/llvm note
- Use LD_LIBRARY_PATH environment variable in build script to remove need to modify build script for ARM devices
- Throw descriptive error message if port ID is invalid
=> Minor config streamlining

core/Cargo.toml
Update dependencies for for https://github.com/stanford-esrg/retina/issues/39
=> update parser dependency to stanford-esrg owned versions

core/src/port/mod.rs
As noted in issue https://github.com/stanford-esrg/retina/issues/38, the RSS offload types is currently hardcoded and not all NICs support the set value. This PR takes the suggestion from @tbarbette and updates the assignment to a value provided by the NIC (dev_info.flow_type_rss_offloads).
I have only tested this on an Intel X710. If @thearossman can test this on the ConnectX-5 and any other hardware they have that would be great.
=> Assign RSS offload type with NIC supported values

core/Cargo.toml, examples/basic/Cargo.toml, examples/client_randoms/Cargo.toml, examples/ip_anon/Cargo.toml, examples/log_conn/Cargo.toml, examples/log_dns/Cargo.toml, examples/log_http/Cargo.toml, examples/log_quic/Cargo.toml, examples/log_tls/Cargo.toml, examples/pcap_dump/Cargo.toml, examples/spin/Cargo.toml, examples/video/Cargo.toml
@sippejw kindly tested Retina on Intel E810 and Intel X710 with the changes in #54. At this point, it makes sense to remove mlx5 from default features. I'm keeping it in the examples for now.
=> Move mlx5 feature dependency to example files

core/Cargo.toml, core/src/protocols/stream/quic/crypto.rs, core/src/protocols/stream/quic/mod.rs
Same as PR #37, updates being that `rust-crypto` has been replaced with `aes-gcm`.
The standard QUIC handshake between two hosts who do not have a pre shared key involves the use of QUIC Initial packets to share a TLS 1.3 client and server hello. After these two messages have been received, the hosts are able to change to new keys unknown to network observers. This PR add the ability to parse QUIC Initial packets, decrypt the protected payloads, parse the QUIC frames, and parse the TLS client and server hello. This gives users the ability to filter QUIC traffic on many of the same features as TLS, such as SNI.
- Fixes bug that causes subtraction overflow panic on short retry packets
- Adds module (`crypto.rs`) for initial key derivation, based on Cloudflare's Quiche
- Decrypts all init …
=> QUIC Initial Packet Decryption and Parsing

core/src/protocols/packet/tcp.rs
Very small change: cast `bool` to `u8` in accessor methods for TCP flags. This allows for filtering on TCP flag values at the packet level by specifying "tcp.flag = 0 | 1" (e.g., "tcp.syn = 1"). 
This is a workaround to changing the filtering language to support boolean values for protocol fields (e.g., "tcp.syn = true" and "tcp.syn" would not work in filters).
Addresses https://github.com/stanford-esrg/retina/issues/46
=> Convert tcp flag accessors to u8 to support filtering

INSTALL.md, README.md
1. In INSTALL, document a mempool creation error that may occur when running applications in offline mode using `configs/offline.toml`. Since offline mode is mainly used to test for functionality, this error can be resolved by reducing the mempool capacity in the config file (e.g. setting the capacity to 8192 works).
2. Add more information to README on how users can start writing their own Retina application.
=> Add documentation for onboarding steps

.github/workflows/rustdoc.yml
Experimenting with the best way to deploy documentation to gh-pages when we have multiple versions. I don't have a site set up to test locally, so I'm submitting a PR here.
=> Fixing documentation deployment

core/src/filter/ptree.rs, datatypes/src/static_type.rs, datatypes/src/typedefs.rs
- Per-packet fields (e.g., TCP flags, length) can't be accessed after the packet filter
If the user tries to specify this, compilation should fail with a helpful error message.
- PacketList and SessionList were not documented in the previous commit.
=> Two documentation changes

datatypes/src/conn_fts.rs, datatypes/src/connection.rs, datatypes/src/lib.rs, datatypes/src/typedefs.rs, filtergen/src/deliver_filter.rs, filtergen/src/packet_filter.rs, filtergen/src/utils.rs
* Document invalid filter (https://github.com/stanford-esrg/retina/issues/66) with error message
* Use `mbufs` where possible at the packet deliver phase when disambiguating between callbacks. This doesn't have a performance impact and may be useful in case we support https://github.com/stanford-esrg/retina/issues/66 in the future.
* Some cleanup to filtergen code: move packet filter codegen to filtergen/utils; remove unused param from gen_pktfilter. 
* This also adds reasonable developer documentation within the `datatypes` crate, which would be needed for anyone adding new datatypes.
=> Add error for https://github.com/stanford-esrg/retina/issues/66; clean up packet filter generation code

core/src/conntrack/conn/conn_info.rs, core/src/protocols/stream/dns/parser.rs, core/src/protocols/stream/http/parser.rs, core/src/protocols/stream/mod.rs, core/src/protocols/stream/quic/parser.rs, core/src/protocols/stream/tls/parser.rs
1. Rename `SessionState` enum to `ParsingState`
2. Rename enum variant `Remove` to `Stop` 
Updating the enum name provides more clarity on what happens during a connection under multi-subscription Retina. `ParsingState` describes whether we're probing, parsing, or done parsing packets in the connection. However, even after we finish parsing packets, the connection may not terminate. For example, if we specify in our callback that we also want to track packet interarrival times, then we continue updating the interarrival times even after we stop parsing, and the connection terminates only once we finish updating the interarrival times.
=> Rename SessionState enum to ParsingState

core/src/lcore/monitor.rs
It was a minor annoyance and sometimes caused mistakes, so I decided to fix it.
I also have a question: in my system, the ingress packets counter is always zero, which makes the percentages to be infinity or NaN. Is it normal? Should I configure something for it?
=> Use Gbps and Mpps units in monitor

core/src/conntrack/conn/conn_info.rs, core/src/conntrack/mod.rs, core/src/dpdk/inlined.c, core/src/dpdk/mod.rs, core/src/filter/datatypes.rs, core/src/filter/ptree.rs, core/src/memory/mbuf.rs, datatypes/src/lib.rs, datatypes/src/packet_list.rs, datatypes/src/typedefs.rs, filtergen/src/lib.rs
Create multiple, user-defined datatypes for caching Mbufs (raw packets) for end of connection delivery.
This also adds infrastructure for sharing Mbufs using DPDK's reference counting infrastructure (see memory/mbuf file). This gives us a way to share Mbufs between multiple data structures (e.g., pre- and post-reassembly) without copying and with lower overhead than Rust's Rc or Arc infrastructure. It may encounter issues if Mbufs are shared across threads, but they will not be in the current architecture. This infrastructure is critical for supporting future streaming datatypes.
Note that, with some of these datatypes, mempool availability can become the bottleneck, especially when working with UDP connections (which cannot be delivered until timeout). In some cases, it is more efficient …
=> Add PacketList Datatypes

core/src/conntrack/conn/conn_info.rs, core/src/conntrack/conn/mod.rs, core/src/conntrack/conn/tcp_conn/mod.rs, core/src/conntrack/conn/tcp_conn/reassembly.rs, core/src/conntrack/mod.rs, core/src/conntrack/pdu.rs, core/src/filter/actions.rs, core/src/filter/datatypes.rs, core/src/filter/ptree.rs, core/src/subscription/mod.rs, datatypes/src/lib.rs, datatypes/src/packet_list.rs, datatypes/src/typedefs.rs, filtergen/src/data.rs
- Performance: clear OOO buffers when reassembly is no longer needed
- Performance: drop tracked Mbufs more greedily
- Update termination heuristic - must see both FINs and both ACKs for FINs
- Some minor cleanup
=> Minor TCP Reassembly and Packet Tracking Changes

core/build.rs
This prevents rerunning the build script after each build, improves the compile time of subsequent builds.
=> Fix typo in `core/build.rs`

configs/online-vdev.toml, core/src/memory/mempool.rs
When mbuf_size(u32) is larger than 65535(for example `online-vdev.toml`), it is silently truncated to u16. This PR fixes it.
=> Avoid mbuf size truncation to u16

datatypes/src/connection.rs
I'm interested in finding out the percentage of traffic bytes used by each reported connection. Currently, `ConnRecord` reports only payload bytes, which excludes malformed packets and ethernet/ip headers. I added a new field `nb_pkt_bytes` to `Flow` in the `ConnRecord` for this propose and renamed the old `nb_bytes` to `nb_payload_bytes` to reduce confusion.
=> Report whole packet bytes in ConnRecord

Cargo.toml, configs/online-vdev.toml, configs/online.toml, core/Cargo.toml, core/src/config.rs, core/src/conntrack/conn/mod.rs, core/src/conntrack/mod.rs, core/src/lcore/monitor.rs, core/src/lcore/rx_core.rs, core/src/lib.rs, core/src/runtime/online.rs, core/src/stats.rs, core/src/stats/mod.rs, core/src/stats/prometheus.rs, core/src/subscription/mod.rs, examples/websites-prometheus/Cargo.toml, examples/websites-prometheus/README.md, examples/websites-prometheus/src/main.rs
This PR adds some statistics using prometheus. Prometheus is a time series database which is widely used for collecting metrics.
This is a per core chart of total bits per second. It is on my local machine with a fake traffic so it is in order of Kbit/s.
I put some effort in making the statistics cost negligible. I store them in thread local variables, and flush them into the atomic ones occasionally (currently every 1000 idle iterations). I also made a parameter for each core even for stats that their per core versions doesn't matter much, in order to prevent contention. To run the prometheus server, I used the main core. Previously it did only monitorings, now it does monitoring and runs a http server for prometheus concurrently using a single threaded tokio runtime.
=> Add prometheus for statistics

core/Cargo.toml, core/src/conntrack/mod.rs, core/src/conntrack/timerwheel.rs, core/src/lcore/monitor.rs, core/src/lcore/rx_core.rs
Previously, timerwheel used `crossbeam_channel::tick::try_recv` function. This function called `Instant::now` to see if it should emit an `Instant`. Calling `Instant::now` requires a syscall and it is not fast enough to be called on each iteration. This PR uses a `now` variable that is occasionally updated, and uses it instead of `crossbeam_channel`. I also replaced the other usage of it with `tokio` and removed the `crossbeam_channel` dependency entirely.
My vtune says this function consumes 20% of the cpu. Its usage is mostly in idle cycles but it is not free in busy cycles. I will try to measure its effect later.
=> Don't call `Instant::now()` on each iteration

core/src/filter/grammar.pest
This PR fixes a minor issue where `byte_re_op` was removed from `bin_op` in the grammar while resolving some merge conflicts.
=> Add back the byte regex operator as a binary operator in the grammar

.github/workflows/ci.yml, .github/workflows/rustdoc.yml, INSTALL.md, core/build.rs, core/src/dpdk/mod.rs, core/src/filter/hardware/flow_item.rs, core/src/memory/mbuf.rs
This PR adds support for DPDK 24.11 while preserving the support for previous DPDK versions.
Changes included in this PR:
- Support for DPDK 24.11 was added.
- CI workflows have been updated to include checks for DPDK 24.11.
- CI workflows have been updated to cache DPDK build.
=> Add support for DPDK 24.11

filtergen/src/lib.rs
This PR documents the crates used for implementing the `contains` and `ByteRe` (byte regex) operators.
=> Document crates used for contains and byte regex operators

filtergen/src/utils.rs
This PR implements support for the not equals operator (`!=`) to be used with strings and bytes. When used with bytes, the value on the LHS of the operator could be of type string or byte.
=> Not equals for strings and bytes

core/src/filter/ast.rs, core/src/filter/grammar.pest, core/src/filter/parser.rs, examples/log_ssh/src/main.rs, filtergen/src/lib.rs, filtergen/src/utils.rs
This PR adds a new binary operator, not contains, which can be used with strings or bytes.
=> not contains operator

core/src/lcore/monitor.rs
This PR improves the readability of the current time output.
=> Pretty print current time.

Cargo.toml, core/src/conntrack/conn/conn_info.rs, core/src/filter/actions.rs, core/src/filter/ast.rs, core/src/filter/datatypes.rs, core/src/filter/hardware/mod.rs, core/src/filter/mod.rs, core/src/filter/pattern.rs, core/src/filter/ptree.rs, core/src/subscription/mod.rs, datatypes/src/lib.rs, datatypes/src/packet_list.rs, datatypes/src/streaming.rs, datatypes/src/typedefs.rs, examples/streaming/Cargo.toml, examples/streaming/src/main.rs, filtergen/src/cache.rs, filtergen/src/data.rs, filtergen/src/lib.rs, filtergen/src/parse.rs, filtergen/src/utils.rs
This PR introduces an interface for specifying that a callback should be invoked every N packets, seconds, or bytes. 
There's a lot more to do to finish out streaming callbacks -- allowing for a mutable datatype and multiple streaming parameters are the two main things -- but I think that this initial version works, and I'd like to get it into main so that folks can start to try it out.
=> Initial Streaming Callbacks
